### PR TITLE
fix(versioncontrol): use persistent path to keep version info

### PR DESCRIPTION
**Pull request by htuna07**

### CODE REVIEW

**Comment by emre2345** [comment]
@htuna07 Can you please explain how this pr fixes the problem?

**Comment by emre2345** [comment]
@htune07 Can you please outline the test cases and expected behaviour for me to test this.

**Comment by emre2345** [comment]
@htuna07 
Can you please outline the test cases and expected behaviour for me to test this.

**Comment by htuna07** [comment]
@emre2345 
1-Create some bucket, function etc.
2-Use git commands to version those changes(**git add .** and **git commit** are enough)
3-Confirm that you have a git commit history
4-Kill the API process, run **yarn bazel clean --expunge** to clear all bazel build files, then start the API
5-You are supposed to see the git commit history as is before
If you can't, it means this PR couldn't fix the bug.

**Review by emre2345 — APPROVED** [review]
LGTM

Tested on my local device

**Pull request merged**
